### ISSUE TITLE
DEB Package broken symlink

### ISSUE THREAD

**Issue by tommaso-perondi** [LINBIT/drbd#12]
Hi guys, building the dkms package for debian generates a broken symlink to drbd_strings.c that fails the dkms build on debian 10 systems. Building normally works ok.

**Comment by rck** [comment]
and which commands do you execute exactly?
from a tarball? which version?
from git? which branch/commit?

please help us to help you by providing some very basic information.

**Comment by tommaso-perondi** [comment]
Sorry, i didn't mean to submit the issue and i didn't notice i had confirmed. I'm using the sources from commit a60cffa, i'm building the package with `pkg-buildpackage -rfakeroot -b -uc`. It generates the deb files without any problems. The issue is when i try to build that package with DKMS, i get this: 
`make[2]: *** No rule to make target '/var/lib/dkms/drbd/9.1.2-1/build/src/drbd/drbd_strings.c', needed by '/var/lib/dkms/drbd/9.1.2-1/build/src/drbd/drbd_strings.o'.  Stop.`
If i check that file(drbd_strings.c) it turns out that it's a symlink to `drbd-headers/drbd_strings.c` wich doesn't exist.
Hope i gave you enough information.
Thanks.

**Comment by rck** [comment]
but in the git checkout you have `drbd-headers/drbd_strings.c`? if not, clone the repo with `--recursive` and try again. If you have the file, then try to generate the `drbd-dkms....deb` via `debuild -us -uc -i -b`. I did exactly that with your commit hash and the following `dpkg -i ../drbd-dkms_9.1.2-1_all.deb` worked perfectly fine. As we use the dkms for example for Proxmox I'm sure we would have had multiple complaints already.

**Comment by tommaso-perondi** [comment]
> but in the git checkout you have `drbd-headers/drbd_strings.c`? if not, clone the repo with `--recursive` and try again. If you have the file, then try to generate the `drbd-dkms....deb` via `debuild -us -uc -i -b`. I did exactly that with your commit hash and the following `dpkg -i ../drbd-dkms_9.1.2-1_all.deb` worked perfectly fine. As we use the dkms for example for Proxmox I'm sure we would have had multiple complaints already.

Ok, it was simpler then i tought, that folder was a submodule, i should've checked, my bad.  Btw it should be included in the readme that the repo contains sub-modules as it's not obvious that it does.
Anyway Thank you for the quick reply!
