### ISSUE TITLE
kernel crash when creating metada (4 nodes)

### ISSUE THREAD

**Issue by SpitchAG** [LINBIT/drbd#14]
Hi,

i bump into a kernel oops quiet regularly resyncronizing 4 nodes that were before distributed in 2 independent clusters of 2 nodes.

I am using AWS VMs and the block device are EBS ones. the lower layer storage are lvm volumes. cluster manager is pacemaker.

The steps i follow are:

- i create 2 independant clusters (both device on each cluster configured whith peers max number to 3, however at this stage they use only 1 peer - i do it to avoid resizing when i move the setup to geo (2+2 devices))

- at this stage my 2 clusters are up, all ok.

- ->from there, i can reproduce the crash doing this:

1. (on all nodes) i change the settings files to add the 2 extra nodes (thus the drbd.conf file now has 4 nodes instead of 2)

2. i shutdown drbd resource on all nodes

3.(on all node) drbdadm create-md --force {{ reource }} --max-peers 3

4. (on all node) drbdadm up {{ resource }}

5. (on ONE node): drbdadm primary --force {{ resource }}data

at this stage crash of one remote peer , around 1/3

drbdadm --version
DRBDADM_BUILDTAG=GIT-hash:\ bd7a08c4ec9cad113c4e5ad448a15c8900a67b68\ build\ by\ root@ip-172-31-12-143.eu-west-1.compute.internal\,\ 2021-08-12\ 15:13:28
DRBDADM_API_VERSION=2
DRBD_KERNEL_VERSION_CODE=0x090103
DRBD_KERNEL_VERSION=9.1.3
DRBDADM_VERSION_CODE=0x091202
DRBDADM_VERSION=9.18.2

[ 4003.283029] BUG: unable to handle kernel NULL pointer dereference at           (null)
[ 4003.292376] IP: [<          (null)>]           (null)
[ 4003.297386] PGD 80000000334ee067 PUD 78a18067 PMD 0
[ 4003.302589] Oops: 0010 [#1] SMP
[ 4003.307168] Modules linked in: drbd_transport_tcp(OE) drbd(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat iptable_mangle iptable_security iptable_raw nf_conntrack ip_set ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter nfit libnvdimm iosf_mbi crc32_pclmul ghash_clmulni_intel aesni_intel ppdev lrw gf128mul glue_helper ablk_helper cryptd pcspkr parport_pc parport i2c_piix4 softdog ip_tables xfs libcrc32c nvme crct10dif_pclmul crct10dif_common crc32c_intel serio_raw ena nvme_core sunrpc dm_mirror dm_region_hash dm_log dm_mod
[ 4003.368720] CPU: 1 PID: 30047 Comm: drbd_w_voicepri Kdump: loaded Tainted: G           OE  ------------   3.10.0-1160.36.2.el7.x86_64 #1
[ 4003.379873] Hardware name: Amazon EC2 t3.small/, BIOS 1.0 10/16/2017
[ 4003.385536] task: ffff9cc336ed8000 ti: ffff9cc33937c000 task.ti: ffff9cc33937c000
[ 4003.395064] RIP: 0010:[<0000000000000000>]  [<          (null)>]           (null)
[ 4003.404608] RSP: 0018:ffff9cc33937fdd0  EFLAGS: 00010246
[ 4003.410242] RAX: 0000000000000000 RBX: ffff9cc33937fe18 RCX: ffffffffc05a232c
[ 4003.416835] RDX: 0000000000000029 RSI: 0000000000000000 RDI: ffff9cc334b0eac8
[ 4003.423364] RBP: ffff9cc33937fe80 R08: 0000000000000c35 R09: 0000000000000140
[ 4003.429837] R10: 00000001003879f5 R11: ffffd50cc0cdae80 R12: ffff9cc334b0e960
[ 4003.436394] R13: ffff9cc334b0eac8 R14: ffff9cc334b0ed08 R15: ffff9cc334b0ed00
[ 4003.442829] FS:  0000000000000000(0000) GS:ffff9cc33d700000(0000) knlGS:0000000000000000
[ 4003.456660] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 4003.463410] CR2: 0000000000000000 CR3: 000000007356e000 CR4: 00000000007606e0
[ 4003.469757] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 4003.475895] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 4003.482058] PKRU: 00000000
[ 4003.486371] Call Trace:
[ 4003.490597]  [<ffffffffc054edc2>] ? drbd_worker+0x112/0x530 [drbd]
[ 4003.496299]  [<ffffffff85ec6f30>] ? wake_up_atomic_t+0x30/0x30
[ 4003.502539]  [<ffffffffc05731a0>] ? do_retry+0x290/0x290 [drbd]
[ 4003.508428]  [<ffffffffc0573256>] drbd_thread_setup+0xb6/0x1f0 [drbd]
[ 4003.515138]  [<ffffffffc05731a0>] ? do_retry+0x290/0x290 [drbd]
[ 4003.529482]  [<ffffffff85ec5e41>] kthread+0xd1/0xe0
[ 4003.534944]  [<ffffffff85ec5d70>] ? insert_kthread_work+0x40/0x40
[ 4003.551754]  [<ffffffff86595df7>] ret_from_fork_nospec_begin+0x21/0x21
[ 4003.562722]  [<ffffffff85ec5d70>] ? insert_kthread_work+0x40/0x40
[ 4003.575279] Code:  Bad RIP value.
[ 4003.585259] RIP  [<          (null)>]           (null)
[ 4003.597228]  RSP <ffff9cc33937fdd0>
[ 4003.608403] CR2: 0000000000000000

**settings**:
resource audiodata {
        startup {
                wfc-timeout  15;
                degr-wfc-timeout 60;
        }
        volume 0 {
                device /dev/drbd0;
                disk /dev/mapper/audio_pool-audio_volume;
                meta-disk internal;
        }
        on ip-172-31-12-50 {
                node-id   0;
                address 172.31.12.50:7788;
        }
        on ip-172-31-12-216 {
                node-id   1;
                address 172.31.12.216:7788;
        }
        connection {
             host ip-172-31-12-50    address 172.31.12.50:7788;
             host ip-172-31-12-216    address 172.31.12.216:7788;
             net {
                protocol C;
                cram-hmac-alg sha1;
                shared-secret "secret";
                after-sb-0pri discard-younger-primary;
                after-sb-1pri discard-secondary;
                after-sb-2pri disconnect;
                                    fencing resource-and-stonith;
                             }
        }
                # begin geo cluster extension
        on ip-172-31-12-206 {
             node-id   2;
             address 172.31.12.206:7788;
        }
        on ip-172-31-12-143 {
                node-id   3;
                address 172.31.12.143:7788;
        }
        # extended local cluster synchronous links
        connection {
             host ip-172-31-12-206   address 172.31.12.206:7788;
             host ip-172-31-12-143   address 172.31.12.143:7788;
             net {
                protocol C;
                cram-hmac-alg sha1;
                shared-secret "secret";
                after-sb-0pri discard-younger-primary;
                after-sb-1pri discard-secondary;
                after-sb-2pri disconnect;
                                    fencing resource-and-stonith;
                             }
        }
        #async links between local clusters
        connection {
             host ip-172-31-12-50       address 172.31.12.50:7788;
             host ip-172-31-12-206   address 172.31.12.206:7788;
             net {
                 protocol A;
             }
        }
        connection {
             host ip-172-31-12-50       address 172.31.12.50:7788;
             host ip-172-31-12-143   address 172.31.12.143:7788;
             net {
                 protocol A;
             }
        }
        connection {
             host ip-172-31-12-216       address 172.31.12.216:7788;
             host ip-172-31-12-206   address 172.31.12.206:7788;
             net {
                 protocol A;
             }
        }
        connection {
             host ip-172-31-12-216       address 172.31.12.216:7788;
             host ip-172-31-12-143   address 172.31.12.143:7788;
             net {
                 protocol A;
             }
        }
        # end geo cluster extension
        handlers {
           
                  }
}

**Comment by Philipp-Reisner** [comment]
@SpitchAG can you verify that commit 3d65de4a027c841948723f9cef62ac9a4cba215a fixes this?

**Comment by SpitchAG** [comment]
Hi,
yes it seems to be fixed, at least cannot reproduce,
thanks
