### ISSUE TITLE
The document translation problem of Chinese

### ISSUE THREAD

**Issue by zeaone** [LINBIT/drbd#16]
the url of this problem:[16.4. 快速同步位图](https://linbit.com/drbd-user-guide/drbd-guide-9_0-cn/)
the position of this problem: At the end of paragraph 16.4, as shown below
![image](https://user-images.githubusercontent.com/15962991/141735172-fc3a5074-1779-4e71-88f2-8eff2b0e7da9.png)

i think the **_"心平气和"_** should translate as  **_"草率"_**

So the whole sentence should be translated like this
使用 drbdadm pause-sync 和`drbdadm resume-sync`命令也可以暂停并手动恢复重新同步。但是，您不应该**草率**地这样做——中断重新同步会使辅助节点的磁盘不一致的时间超过必要的时间。

**Comment by JoelColledge** [comment]
Thank you for your interest in contributing. The user's guide is maintained at https://github.com/LINBIT/linbit-documentation Please open an issue there instead.
