### ISSUE TITLE
“drbdadm -h” lacks "sh-dev" and "sh-ll-dev"

### ISSUE THREAD

**Issue by devlikai** [LINBIT/drbd#19]
“drbdadm -h” lacks "sh-dev" and "sh-ll-dev". But drbdadm supports "sh-dev" and "sh-ll-dev".

root@ecs-drbd-primary:~# drbdadm --help | grep sh- 
  --sh-varname=..., -n ...

**Comment by rck** [comment]
intentional. `drbdadm hidden-commands -h`
