### ISSUE TITLE
Building drbd 9.1.5 Centos Image

### ISSUE THREAD

**Issue by gsexton** [LINBIT/drbd#25]
I'm trying to build the centos7 kernel injection image and getting a file not found:

https://pkg.linbit.com/downloads/drbd/9/drbd-9.1.5-1.tar.gz

this seems to work:

https://pkg.linbit.com/downloads/drbd/9/drbd-9.1.5.tar.gz

Should that be updated?

**Comment by JoelColledge** [comment]
This should have been fixed in 7084bb2f778f324f9b8ccf2869cadbeca1db9132. Try using that commit instead of the `drbd-9.1.5` tag. Note that the Dockerfile is now called `Dockerfile.rhel7`. It is still based on the `ubi7` image.

**Comment by JoelColledge** [comment]
Closing issue because this appears to have been fixed in the code and there has been no response to the contrary.
