### ISSUE TITLE
DRBD9 on Debian 11

### ISSUE THREAD

**Issue by Snowmanko** [LINBIT/drbd#34]
Hi,
i cant find prebuild packages for Debian 11 anywhere, docs also dont mention whats the correct repo. Can you please provide any source of infos where / how can I deploy DRBD 9.x on Debian platform? (I dont want to build from sources)

BR!

**Comment by rck** [comment]
As answered per mail:

The only source of pre-built Debian kernel modules for current versions of DRBD I'd be aware are our (= LINBIT's ) customer repositories. If you are interested getting access, are access to other LINBIT services, please talk to sales@linbit.com
