### ISSUE TITLE
Does DRBD support two different network segment IP addresses (each machine)

### ISSUE THREAD

**Issue by likunyur** [LINBIT/drbd#36]
When DRBD is at the IP address of a single network segment (each machine), the abnormal network interface may lead to brain fissure of DRBD.
Does DRBD currently support two different network segment addresses (per machine)? If not, please tell me which part of the code should be modified. I could try to modify the following.

Thanks!

li kunyu

**Comment by kermat** [comment]
Hello @likunyur 

I apologize that this issue slipped through the cracks and did not get a response.

DRBD v9 does support multiple paths as documented in the [DRBD User's Guide](https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-configuring-multiple-paths).

Cheers
