### ISSUE TITLE
Mounting drbd not working

### ISSUE THREAD

**Issue by philipphomberger** [LINBIT/drbd#53]
Than I try mounting the DRBD Device I get this error:

`
[eco_adm@cg3a54d9ac-mstrfs-s302 opt]$ sudo mount --all
mount: /opt/mstrtf: mount(2) Systemaufruf ist fehlgeschlagen: Wrong medium type.

`

Here the Status of the Cluster:
`
[eco_adm@cg3a54d9ac-mstrfs-s302 mstrtf]$ drbdsetup status -vs
r0 node-id:1 role:Secondary suspended:no force-io-failures:no
    write-ordering:flush
  volume:0 minor:0 disk:UpToDate backing_dev:/dev/vdb quorum:yes
      size:20970844 read:0 written:20970844 al-writes:0 bm-writes:403 upper-pending:0 lower-pending:0 al-suspended:no blocked:no
  cg3a54d9ac-mstrfs-s301.sys.schwarz node-id:0 connection:Connected role:Primary congested:no ap-in-flight:0 rs-in-flight:0
    volume:0 replication:Established peer-disk:UpToDate resync-suspended:no
        received:20970844 sent:0 out-of-sync:0 pending:0 unacked:0
`
Here the config file: 

`
[eco_adm@cg3a54d9ac-mstrfs-s302 opt]$ cat /etc/drbd.d/global_common.conf
global {
	usage-count no;
}

common {
  disk {
  }
  net {
    cram-hmac-alg sha1;
    shared-secret "****";
  }
  handlers {
  }
  startup {
  }
  options {
  }
}

resource r0 {
  on cg3a54d9ac-mstrfs-s301.sys.schwarz {
    device /dev/drbd0;
    disk /dev/vdb;
    address 10.124.141.15:7788;
    meta-disk internal;
  }
  on cg3a54d9ac-mstrfs-s302.sys.schwarz {
    device /dev/drbd0;
    disk /dev/vdb;
    address 10.124.141.228:7788;
    meta-disk internal;
  }
}
`
Here the fstab config 

`
UUID=08d8ba03-a737-4caa-80fe-bdcf160bb8e9 /                       xfs     defaults        0 0
UUID=3a94b570-1121-4bbd-8c1e-beb2b73d0c03 /boot                   xfs     defaults        0 0
UUID=0607-95FB          /boot/efi               vfat    defaults,uid=0,gid=0,umask=077,shortname=winnt 0 2
/dev/drbd0 /opt/mstrtf ext4 defaults 0 0`

As anybody a Idea why this is happen ? 
Thank You

**Comment by rck** [comment]
it is Primary on `s301`, you obviously will not be able to mount it on `s302`.

**Comment by philipphomberger** [comment]
Thank You for the fast feedback :)
