### ISSUE TITLE
DRBD 9.2.5 build failure on Arch Linux with kernel 6.5.3

### ISSUE THREAD

**Issue by Ickowsky** [LINBIT/drbd#69]
**The error:**

CC [M]  /root/drbd/drbd-9.2.5/drbd/drbd_main.o
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:169:27: error: initialization of ‘int (*)(struct gendisk *, blk_mode_t)’ {aka ‘int (*)(struct gendisk *, unsigned int)’} from incompatible pointer type ‘int (*)(struct block_device *, fmode_t)’ {aka ‘int (*)(struct block_device *, unsigned int)’} [-Werror=incompatible-pointer-types]
  169 |         .open           = drbd_open,
      |                           ^~~~~~~~~
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:169:27: note: (near initialization for ‘drbd_ops.open’)
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:170:27: error: initialization of ‘void (*)(struct gendisk *)’ from incompatible pointer type ‘void (*)(struct gendisk *, fmode_t)’ {aka ‘void (*)(struct gendisk *, unsigned int)’} [-Werror=incompatible-pointer-types]
  170 |         .release        = drbd_release,
      |                           ^~~~~~~~~~~~
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:170:27: note: (near initialization for ‘drbd_ops.release’)
/root/drbd/drbd-9.2.5/drbd/drbd_main.c: In function ‘inc_open_count’:
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:2631:32: error: ‘FMODE_NDELAY’ undeclared (first use in this function); did you mean ‘O_NDELAY’?
 2631 |         enum ioc_rv r = mode & FMODE_NDELAY ? IOC_ABORT : IOC_SLEEP;
      |                                ^~~~~~~~~~~~
      |                                O_NDELAY
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:2631:32: note: each undeclared identifier is reported only once for each function it appears in
/root/drbd/drbd-9.2.5/drbd/drbd_main.c: In function ‘drbd_open’:
/root/drbd/drbd-9.2.5/drbd/drbd_main.c:2758:78: error: ‘FMODE_NDELAY’ undeclared (first use in this function); did you mean ‘O_NDELAY’?
 2758 |                                 rv = try_to_promote(device, timeout, (mode & FMODE_NDELAY));
      |                                                                              ^~~~~~~~~~~~
      |                                                                              O_NDELAY
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:243: /root/drbd/drbd-9.2.5/drbd/drbd_main.o] Error 1
make[1]: *** [Makefile:2032: /root/drbd/drbd-9.2.5/drbd] Error 2
make: *** [Makefile:134: kbuild] Error 2

**Comment by dvance** [comment]
Which distro and kernel are you trying to build this for specifically?

**Comment by Ickowsky** [comment]
> Which distro and kernel are you trying to build this for specifically?

Arch Linux, kernel 6.5.3 ---- It's in the title

**Comment by Ickowsky** [comment]
The https://github.com/LINBIT/drbd/commit/4a84d1d0915ac764652a8083b084f7e1cafd0122 commit solves the issue, waiting for 9.2.6 tag.
