### ISSUE TITLE
Very low write speeds

### ISSUE THREAD

**Issue by ShiZNizZLe** [LINBIT/drbd#70]
Hello,

Currently we are running 2 servers with a drbd configuration:
The machine we're logged into in this picture is the v02, where drbd1 is primary.
![image](https://github.com/LINBIT/drbd/assets/15122459/b9bcc5a1-269f-4cc0-9ca8-042cc737c9b2)

Here we run a Windows 2022 server with the following startup rules:
(originally we use aio=native, cache.direct=on)
![image](https://github.com/LINBIT/drbd/assets/15122459/efa7a9af-e624-46ef-a7cd-03f985b39d71)

Our harddisk is a WD nvme drive. 
Ofcourse we want to see the high read/write numbers that this drive offers.
We did a lot of benchmarks with various flags disabled and enabled as mentioned above.
We also switched from 'virtio-blk' as device to 'nmve' which resulted in lower performance.

The problem:
When the drbd is synced and connected the benchmark results look like this:
![image](https://github.com/LINBIT/drbd/assets/15122459/3fc772b5-c93b-4324-ac7a-b014dc448bcc)

When we give the command 'drbdadm disconnect drbd0' and 'drbdadm disconnect drbd1' the benchmark results look like this:
![image](https://github.com/LINBIT/drbd/assets/15122459/d813a417-0a82-4076-8f91-e239448e5b02)

We already adjusted the /etc/drbd.conf:
- changing protocol version, 
- changing maxbuffer & maxepoch
- setting c-plan-ahead to 0
- adjusting resyncrate
- adjusting rate
![image](https://github.com/LINBIT/drbd/assets/15122459/367e85ab-33c4-4b6e-afce-dde28a965256)

Unfortunately nothing changed the result of the low write speeds when drbd is connected and in sync.

What could be the bottleneck why the writespeed is capped at ~115MB/s when the drbd is functioning normally?

**Comment by dvance** [comment]
The output of the first picture looks like `/proc/drbd` output from 8.4.x branch of DRBD. That's been deprecated for some time now. We're not going to investigate a 5-year-old version from a now archived branch. Could you let us know specifically what version this is?

DRBD replicates over the network. Have you done any benchmarking of the network between the hosts? 115MiB/s is what I would expect with a gigabit network.

There are a lot of moving parts with the addition of the VMs running atop DRBD. Like most performance testing/troubleshooting, I generally advise starting from "the bottom up" test the hardware directly, and then begin to add layers to it and test each one as you do so.

**Comment by dvance** [comment]
Spoke via the slack (https://linbit-community.slack.com/). Seems the issue is a 1GiB network.
>i thought of the possibility that the cap comes from a 1gbit connection but why? because the server is running on the primary side locally. It shouldn't have to be dependant on the secondary side. the syncing can take place asynchronously right?

DRBD can replicate asynchronously, but...
With fully synchronous replication we send the write over to the peer and wait for an ACK back. Once we know the write has hit the disk of both peers, we consider the write complete locally. With asynchronous replication, we consider a write complete once a write has hit the local disk and has been placed into the TCP send buffers to go off onto the peer node. ...So, what happens when those TCP send buffers fill up? We have to wait for it to drain before we can place another write into it. So, now we're backed up and again running at just 1GiB/s.

**Comment by ShiZNizZLe** [comment]
Thanks for the update @dvance now you explained it it's clear for us too. I didn't know we were using an old drbd version, i guess it won't change anything for this problem though. Thanks for your help :)
