### ISSUE TITLE
Unable to demote DRBD devices since it is opened by Multipath 

### ISSUE THREAD

**Issue by ramzcode** [LINBIT/drbd#74]
OS: ubuntu 20.04 LTS
drbd-utils Version: 9.11.0
Environment: AWS

Unable to demote from Primary to Secondary since it is opened by / used by Multipathd. We have not configured anything additionally with Multipath too.

I had to stop and disable the multipathd service so that i can promote and demote the states as usual.

#drbdadm secondary had
1: State change failed: (-12) Device is held open by someone
Command 'drbdsetup-84 secondary 1' terminated with exit code 11

root@ip-172-31-8-207:/# lsof /dev/drbd1 
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
multipath 333 root    5r   BLK  147,1      0t0  350 /dev/drbd1

root@ip-172-31-8-207:/# ps -p 333
    PID TTY          TIME CMD
    333 ?        00:00:08 multipathd

root@ip-172-31-8-207:/# cat /etc/multipath.conf 
defaults {
    user_friendly_names yes
}

Please share thought on this issue, thanks in advance.

**Comment by rck** [comment]
> Please share thought on this issue, thanks in advance.

don't use software that is over 4 years old when you don't want to run into bugs that got fixed over 3 years ago... https://github.com/LINBIT/drbd-utils/commit/7df568757725107bf2e0bb3059855571484861b9

**Comment by ramzcode** [comment]
Great, like i thought need to blacklist it. BTW why there are no update since 9.11 for U20 and 9.15 for U22?

**Comment by rck** [comment]
We are upstream here, that is a question for the Ubuntu maintainers when, how, if they update and which issues they fix. most likely this is an issue nobody made them aware of.

 We provide up to date software for your customers including all supported Ubuntu LTS releases as part of our support subscription.

**Comment by ramzcode** [comment]
Thanks for the clarity, actually it is far worse in 18.04. Thanks again @rck
