### ISSUE TITLE
9.2.6 - unknown tls symbols with Kernel 6.1.60 LTS

### ISSUE THREAD

**Issue by 1848** [LINBIT/drbd#76]
Build env: Arch Linux with 6.1.60-1-lts kernel
drbd.ko loads fine but drbd_transport_tcp.ko fails due to unknown symbols:

>drbd_transport_tcp: Unknown symbol tls_server_hello_x509 (err -2)
> drbd_transport_tcp: Unknown symbol tls_handshake_cancel (err -2)
> drbd_transport_tcp: Unknown symbol tls_client_hello_x509 (err -2)

Those symbols are not part of the kernel until 6.4.
Maybe there is a new compat patch needed for kernel < 6.4?

**Comment by WanzenBug** [comment]
That patch does exist. Or to be more precise, there is a `handshake.ko` which provides compatibility by back-porting the `net/handshake` module from upstream.

How did you build DRBD 9.2.6? From the release tarball?

**Comment by WanzenBug** [comment]
See https://github.com/LINBIT/drbd/blob/52144c0f90a0fb00df6a7d6714ec9034c7af7a28/drbd/Kbuild#L31-L38C4

There may be an issue if you have `CONFIG_TLS=n` for your kernel?

**Comment by WanzenBug** [comment]
I guess so. Usually this is just handled by running `make install` and then `depmod -a` should pick up the required dependencies.
