### ISSUE TITLE
drbdadm create-md always results in "BAD LUCK, equal hashes"

### ISSUE THREAD

**Issue by docholiday** [LINBIT/drbd#81]
Hi there, I am using RHEL 9 and have installed the following packages:

drbd-selinux-9.26.0-1.el9.x86_64
drbd-utils-9.26.0-1.el9.x86_64
drbd-udev-9.26.0-1.el9.x86_64
drbd-9.26.0-1.el9.x86_64

and from elREPO:
kmod-drbd9x-9.1.17-2.el9_3.elrepo.x86_64

When I try to create a resource with
drbdadm create-md myresourcename

I get the result:
`BAD LUCK, equal hashes`

I got this error even before installing the kmod package, but then it was
```
modinfo: ERROR: Module drbd not found.
BAD LUCK, equal hashes
```

Do I have to reset something, due to the fact that I ran the command already, when the module was not present?
Or what could be the problem here?

I searched the web for answers, but found exactly nothing.
Seems like I'm the first one, to get that error...

**Comment by dvance** [comment]
This error is hinting to issues with the node ID hashes. `drbdadm` tries to generate node IDs based on the node names and IPs. If you're really unlucky it could be a genuine hash collision. More likely this is a misconfiguration issue with the same node specified twice or something similar.
Regardless, you should be able to resolve this by explicitly specifying node IDs.

**Comment by docholiday** [comment]
Thank you very much for the hint!
While the hostnames where correct, I had indeed put the same IP twice in the config.
After correcting that, it worked like a charm :-)
