### ISSUE TITLE
is it possible to serve >100 clients (diskless drbd node) with 3 ~ 5 drbd server nodes?

### ISSUE THREAD

**Issue by qiongzhu** [LINBIT/drbd#83]
According to the page ( https://linbit.com/blog/drbd-hardware-environment-requirements/ ), there is a node number limit applied to the drbd cluster:

> Maximum Number of Nodes Accessing a Resource
> There is a limit of 32 nodes that can access the same DRBD resource concurrently. In practice, clusters of more than five nodes are not recommended.

Here is the question: is it possible to serve >100 clients (diskless drbd node) with 3 ~ 5 drbd server nodes? let's assume that the storage traffic is light weighted, also network bandwidth is not a problem.

**Comment by Philipp-Reisner** [comment]
@qiongzhu When each of the >100 clients wants to use its own DRBD resource, its own private data volume, then the answer is: yes!

In the context of the above-quoted documentation snippet, Each DRBD resource is then a DRBD cluster of, e.g., 3 nodes: two on the "server nodes" that have backing storage and 1 diskless node on the "client" machine.
